dependencies:
 - python=3.5
 - numpy
 - scipy
 - scikit-learn
 - jupyter
 - requests
 - pandas
 - seaborn
 - click
 - openpyxl
 - pip:
   - watermark
   - pytest
   - flask-restful
   - scikit-plot
   - nose
