site_name: Cookiecutter Data Science
site_description: Updated and adapted cookcutter data science templates. Originally from drivendata.
site_favicon: favicon.ico
repo_url: https://github.com/mdavis7771/cookiecutter-data-science
copyright: 2018 Michael A. Davis, originally from <a target=_blanks href="https://www.drivendata.org">DrivenData</a>.
google_analytics: ['UA-XXXXXXX-4', 'auto']
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
